Add initial lua files.
CFC-Servers/cfc_help pull request #1
Opened 2020-10-28 23:38 UTC by wrefgtzweve

Adds the initial client lua file.

2020-11-01 16:50 UTC, plally requested changes

2020-11-01 16:50 UTC, plally commented on lua/autorun/client/cl_cfc_help.lua
> +    draw.RoundedBox( 8, 0, 0, w, h, Color( 36, 41, 67, 255 ) )
indent this and perhaps put this color in a constant at the top of the file

2020-11-01 16:50 UTC, plally commented on lua/autorun/client/cl_cfc_help.lua
> +local function hideScrollbar ()
```suggestion
local function hideScrollbar()
```

2020-11-01 16:50 UTC, plally commented on lua/autorun/client/cl_cfc_help.lua
> +
```suggestion
```

2020-11-01 16:50 UTC, plally commented on lua/autorun/client/cl_cfc_help.lua
> +    if string.sub( msg, 1, 5 ) ~= "!help" then return end
https://wiki.facepunch.com/gmod/string.StartWith
using StartsWith will make it easier to change this later

2020-11-01 16:50 UTC, plally commented on lua/autorun/client/cl_cfc_help.lua
> +    html:OpenURL("https://cfcservers.org/learn/")
```suggestion
    html:OpenURL( "https://cfcservers.org/learn/" )
```

2020-11-08 02:44 UTC, brandonsturgeon approved these changes

2020-11-08 02:47 UTC, plally approved these changes

2020-11-08 02:56 UTC, merged